# The Python ecosystem - The NumPy library

[NumPy](http://www.numpy.org/) is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities



In [12]:
import numpy as np

### The array object

In [13]:
x = np.array([1,3,5,7,9,11,13])
x

array([ 1,  3,  5,  7,  9, 11, 13])

In [14]:
x.shape

(7,)

In [15]:
x/100

array([0.01, 0.03, 0.05, 0.07, 0.09, 0.11, 0.13])

In [16]:
xx = x*100
xx

array([ 100,  300,  500,  700,  900, 1100, 1300])

#### Indexing and filtering

In [17]:
xx[0]

100

In [18]:
xx[0:3]

array([100, 300, 500])

**Logical indexing**

In [19]:
xx > 500

array([False, False, False,  True,  True,  True,  True])

In [20]:
xx[xx >= 500]

array([ 500,  700,  900, 1100, 1300])

#### Multidimensional arrays

In [21]:
w = np.array(([1,2,3], [4,5,6]))
print(w.shape)
w

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
w[0]

array([1, 2, 3])

In [23]:
w[0,0]

1

In [24]:
w[0:,1]

array([2, 5])

#### Some basic methods

In [25]:
print("Dimensions: ", w.shape)
w_transposed = w.T
print("Dimensions after transpose ", w_transposed.shape)
w_transposed

Dimensions:  (2, 3)
Dimensions after transpose  (3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
w_transposed.reshape(-1,1)

array([[1],
       [4],
       [2],
       [5],
       [3],
       [6]])

In [27]:
X = np.arange(100).reshape(2, 5, 10)
print(X.shape)
X

(2, 5, 10)


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [28]:
X

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [29]:
# Return random floats in the half-open interval [0.0, 1.0)
xx = np.random.random(10000)
xx

array([0.01697692, 0.60368822, 0.8733904 , ..., 0.76702277, 0.94768328,
       0.50101329])